#!/bin/bash
# update.sh — Regenerate listing + pages for tldrh from Hermes sources
# Usage: ./update.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TLDRH_BIN="${TLDRH_BIN:-$HOME/.local/bin/tldrh}"
TLDRH_PAGES="${TLDRH_PAGES:-$HOME/.local/share/tldrh/pages}"
REPORTS_DIR="$SCRIPT_DIR/reports"

# ── Source check ──────────────────────────────────────────────────────────

echo "🔍 Checking sources..."

required=(
    "$SCRIPT_DIR/sources.py"
    "$SCRIPT_DIR/generate_listing.py"
    "$SCRIPT_DIR/generate_pages.py"
    "$SCRIPT_DIR/exclusions.yaml"
    "$SCRIPT_DIR/notes.yaml"
    "$SCRIPT_DIR/examples.yaml"
)

missing=0
for f in "${required[@]}"; do
    if [ ! -f "$f" ]; then
        echo "  ❌ $f — not found"
        missing=$((missing + 1))
    fi
done

if [ "$missing" -gt 0 ]; then
    echo ""
    echo "❌ $missing source file(s) missing. Aborting."
    exit 1
fi

echo "  ✅ All source files present"
echo ""

# ── Generation ────────────────────────────────────────────────────────────

echo "📡 Generating listing..."
python3 "$SCRIPT_DIR/generate_listing.py"
echo ""

echo "📝 Generating pages..."
python3 "$SCRIPT_DIR/generate_pages.py"
echo ""

# ── Examples diff ──────────────────────────────────────────────────────────

echo "📋 Checking examples.yaml against current commands..."

mkdir -p "$REPORTS_DIR"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT="$REPORTS_DIR/examples-diff-$TIMESTAMP.md"

export SCRIPT_DIR REPORTS_DIR

python3 << 'PYEOF'
import os, sys, yaml, datetime
sys.path.insert(0, os.environ['SCRIPT_DIR'])
from sources import parse_command_defs, load_examples, load_exclusions

timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
reports_dir = os.environ['REPORTS_DIR']
report_path = os.path.join(reports_dir, f'examples-diff-{timestamp}.md')

# Load current commands
excluded = load_exclusions()
cmd_defs = parse_command_defs()

current = set()
for name, d in cmd_defs.items():
    if name in excluded:
        continue
    if d.get('gateway_only'):
        continue
    current.add(name)

# Commands in examples.yaml
examples = load_examples()
in_examples = set(examples.keys())

# Orphaned: in examples.yaml but no longer a command
orphaned = sorted(in_examples - current)

# New: in current commands but not in examples.yaml
new_cmds = sorted(current - in_examples)

# Determine group for display
def count_arg_groups(hint):
    depth = 0
    groups = 0
    for c in hint:
        if c == '[': depth += 1
        elif c == ']': depth -= 1
        if depth == 1 and c == '[': groups += 1
    return groups

def hint_to_group(name):
    d = cmd_defs.get(name, {})
    hint = d.get('args_hint', '') or ''
    n = count_arg_groups(hint)
    notes_path = os.path.join(os.environ['SCRIPT_DIR'], 'notes.yaml')
    is_note = name in yaml.safe_load(open(notes_path)) if os.path.exists(notes_path) else False
    if is_note: return 'note'
    if n == 0: return '0 arg'
    if n == 1: return '1 arg'
    return '2+ args'

has_diff = len(orphaned) > 0 or len(new_cmds) > 0

if not has_diff:
    print('  ✅ examples.yaml is up to date — no changes detected')
    sys.exit(0)

# Generate report
lines = []
lines.append('# tldrh — Examples diff')
lines.append('')
lines.append(f'Generated: {timestamp}')
lines.append('')
lines.append('This file is automatically generated by update.sh.')
lines.append('When new Hermes commands appear or commands are removed,')
lines.append('they are listed below. Add or remove entries in examples.yaml')
lines.append('then re-run update.sh. You may delete this file after fixing.')
lines.append('')

if new_cmds:
    lines.append('## ➕ New commands (missing examples)')
    lines.append('')
    lines.append('| Command | args_hint | Group |')
    lines.append('|---------|-----------|-------|')
    for name in new_cmds:
        d = cmd_defs.get(name, {})
        hint = d.get('args_hint', '') or '-'
        group = hint_to_group(name)
        lines.append(f'| {name} | {hint} | {group} |')
    lines.append('')

if orphaned:
    lines.append('## ➖ Orphaned examples (command removed)')
    lines.append('')
    lines.append('| Command | args_hint |')
    lines.append('|---------|-----------|')
    for name in orphaned:
        d = cmd_defs.get(name, {})
        hint = d.get('args_hint', '') or '-'
        lines.append(f'| {name} | {hint} |')
    lines.append('')

if new_cmds and orphaned:
    updated = sorted(current)
elif new_cmds:
    updated = sorted(current - set(orphaned))
else:
    updated = sorted(current)

lines.append('## ✅ Commands with examples')
lines.append('')
lines.append(', '.join(updated))
lines.append('')

report_text = '\n'.join(lines)
with open(report_path, 'w') as f:
    f.write(report_text)

print(f'  ⚠ {len(new_cmds)} new, {len(orphaned)} orphaned — see report')
PYEOF

# If report was generated, show the summary lines
if [ -f "$REPORT" ]; then
    REPORT_SIZE=$(wc -l < "$REPORT")
    if [ "$REPORT_SIZE" -gt 3 ]; then
        echo ""
        echo "   Report: $REPORT"
    fi
fi

echo ""

# ── Copy to runtime ──────────────────────────────────────────────────────

echo "📦 Copying to runtime locations..."

mkdir -p "$TLDRH_PAGES"
cp "$SCRIPT_DIR/pages/_listing.md" "$TLDRH_PAGES/_listing.md"
cp "$SCRIPT_DIR/pages/"*.page.md "$TLDRH_PAGES/"

if [ -f "$SCRIPT_DIR/tldrh" ]; then
    mkdir -p "$(dirname "$TLDRH_BIN")"
    cp "$SCRIPT_DIR/tldrh" "$TLDRH_BIN"
    chmod +x "$TLDRH_BIN"
fi

# ── Summary ─────────────────────────────────────────────────────────────

page_count=$(ls "$TLDRH_PAGES"/*.page.md 2>/dev/null | wc -l)

echo ""
echo "✅ tldrh updated"
echo "   Pages  : $page_count"
echo "   Listing: $TLDRH_PAGES/_listing.md"
echo "   Wrapper: $TLDRH_BIN"
echo ""
echo "   tldrh           — list commands"
echo "   tldrh compress  — help page for a command"
